// Скриншоты интерфейса для пояснительной записки: `npm run screenshots` (стенд поднят, seed выполнен).
// Файлы складываются в frontend/screenshots/ (в git не попадают).
import { chromium } from '@playwright/test'
import { mkdirSync } from 'node:fs'

const base = process.env.E2E_BASE_URL ?? 'https://localhost:8443'
const out = new URL('../screenshots/', import.meta.url)
mkdirSync(out, { recursive: true })

const browser = await chromium.launch({ channel: process.env.PW_CHANNEL || 'msedge' })
const page = await browser.newPage({ viewport: { width: 1360, height: 820 }, locale: 'ru-RU', ignoreHTTPSErrors: true })
const shot = (name) => page.screenshot({ path: new URL(`${name}.png`, out).pathname.replace(/^\/(\w:)/, '$1') })

await page.goto(base)
await page.waitForSelector('#username')
await shot('01-login')
await page.fill('#username', 'faculty_admin')
await page.fill('#password', 'demo-password-1')
await page.click('#kc-login')
// После входа — рабочий стол (фаза 8)
await page.waitForSelector('.stat')
await page.waitForTimeout(800)
await shot('02-home')
await page.goto(`${base}/units`)
await page.waitForSelector('.p-treetable-tbody tr')
await page.waitForTimeout(800)
await shot('02-units')

await page
  .locator('.p-treetable-tbody tr', { hasText: '3 курс, факультет 1' })
  .getByRole('button', { name: 'Перенести' })
  .click()
await page.locator('.p-treeselect').click()
await page.waitForTimeout(400)
await shot('03-move')

await page.keyboard.press('Escape')
await page.goto(`${base}/people`)
await page.waitForSelector('.p-datatable-tbody tr .fio')
await page.waitForTimeout(500)
await shot('04-people')
await page.locator('.p-datatable-tbody tr .fio').first().click()
await page.waitForSelector('h1')
await page.waitForTimeout(600)
await shot('05-person')
await page.getByRole('tab', { name: /Освобождения/ }).click()
await page.waitForTimeout(300)
await shot('06-person-exemptions')

// Фаза 2b: наряды с ролями и требованиями, допуски, отчёт о несоответствиях
await page.goto(`${base}/duty-types`)
await page.waitForSelector('.duty')
await page.waitForTimeout(400)
await shot('07-duty-types')
await page.getByRole('button', { name: 'Изменить роль Помощник дежурного по факультету' }).click()
await page.waitForTimeout(400)
await shot('08-duty-role')
await page.keyboard.press('Escape')

await page.goto(`${base}/people`)
await page.waitForSelector('.p-datatable-tbody tr .fio')
await page.locator('.p-datatable-tbody tr', { hasText: 'Курсант' }).nth(2).locator('.fio').click()
await page.getByRole('tab', { name: /Допуски/ }).click()
await page.waitForTimeout(400)
await shot('09-person-clearances')
await page.getByRole('button', { name: 'Выдать допуск' }).click()
await page.locator('#cl-role').click()
await page.waitForTimeout(400)
// Роли офицеров курсанту недоступны: категория — строгое условие (ADR-0018)
await shot('10-clearance-options')
await page.getByRole('option', { name: /Дежурный по курсу/ }).click()
await page.waitForTimeout(400)
await shot('10-clearance-warning')
await page.keyboard.press('Escape')

await page.goto(`${base}/reports/clearance-mismatches`)
await page.waitForSelector('.p-datatable-tbody tr')
await page.waitForTimeout(400)
await shot('11-clearance-mismatches')

// Фаза 3a: график факультета на следующий месяц с делегированием курсам
const next = new Date(new Date().getFullYear(), new Date().getMonth() + 1, 1)
const nextMonth = `${next.getFullYear()}-${String(next.getMonth() + 1).padStart(2, '0')}-01`
await page.goto(`${base}/schedules?month=${nextMonth}`)
await page.waitForSelector('.grid td.cell')
const dutyCells = page.locator('tr', { hasText: 'Дежурный по факультету' }).locator('td.cell')
await dutyCells.nth(2).click()
await dutyCells.nth(6).click({ modifiers: ['Shift'] })
await page.waitForTimeout(400)
await shot('12-schedule')
await page.keyboard.press('Escape')
await dutyCells.nth(11).dblclick()
await page.waitForSelector('.cell-panel .p-datatable-tbody tr')
await page.waitForTimeout(500)
await shot('13-cell-panel')

// Фаза 4b: предпросмотр автораспределения с объяснением решения
await page.goto(`${base}/schedules?month=${nextMonth}`)
await page.waitForSelector('.grid td.cell')
await page.getByRole('button', { name: 'Распределить…' }).click()
await page.getByRole('button', { name: 'Рассчитать' }).click()
await page.waitForSelector('.panel')
if ((await page.locator('td.cell.proposed').count()) > 0) await page.locator('td.cell.proposed').first().click()
await page.waitForTimeout(500)
await shot('14-allocation-preview')
await page.getByRole('button', { name: 'Отменить' }).click()

// Фаза 6: печать графика, реквизиты и шаблоны, импорт, дашборд нагрузки
await page.goto(`${base}/schedules?month=${nextMonth}`)
await page.waitForSelector('.grid td.cell')
await page.getByRole('button', { name: 'Печать…' }).click()
await page.getByText('Ведомость суточного наряда на дату').click()
await page.waitForTimeout(400)
await shot('15-print')
await page.keyboard.press('Escape')

await page.goto(`${base}/documents`)
await page.waitForSelector('#req-approver_position')
await page.waitForTimeout(500)
await shot('16-documents')

await page.goto(`${base}/import`)
await page.waitForSelector('text=Скачать шаблон')
const csv = [
  'Фамилия;Имя;Подразделение;Категория',
  'Скриншотов;Иван;Факультет управления / 1 курс, факультет 1 / Группа 111;Курсант',
  ';Пётр;Факультет управления / 1 курс, факультет 1 / Группа 111;Курсант',
].join('\n')
await page.locator('[data-testid=import-file]').setInputFiles({ name: 'люди.csv', mimeType: 'text/csv', buffer: Buffer.from(csv) })
await page.waitForSelector('text=создать 1')
await page.getByText(/^Все \(/).click()
await page.waitForTimeout(500)
await shot('17-import-preview')
await page.getByRole('button', { name: 'Отменить', exact: true }).click()

const last = new Date(next.getFullYear(), next.getMonth() + 1, 0)
const lastDay = `${nextMonth.slice(0, 8)}${String(last.getDate()).padStart(2, '0')}`
await page.goto(`${base}/dashboard?from=${nextMonth}&to=${lastDay}&drafts=1`)
await page.waitForSelector('canvas')
await page.waitForTimeout(1200)
await shot('18-dashboard')
await page.getByRole('tab', { name: /Справедливость/ }).click()
await page.waitForTimeout(1200)
await shot('18b-fairness')
await page.getByRole('tab', { name: /Календарь/ }).click()
await page.waitForTimeout(1200)
await shot('18c-calendar')
await page.getByRole('tab', { name: /Конструктор/ }).click()
await page.waitForTimeout(600)
await page.getByRole('combobox', { name: 'Без разбивки' }).click().catch(() => undefined)
await page.getByRole('option', { name: 'Категория личного состава' }).click().catch(() => undefined)
await page.waitForTimeout(1200)
await shot('18d-pivot')
// Тёмная тема: рабочий стол и аналитика
await page.getByRole('button', { name: 'Включить тёмную тему' }).click()
await page.waitForTimeout(800)
await shot('18e-dashboard-dark')
await page.goto(`${base}/home`)
await page.waitForSelector('.stat')
await page.waitForTimeout(1500)
await shot('18f-home-dark')
await page.getByRole('button', { name: 'Включить светлую тему' }).click()

// Фаза 7: операторы и сводный журнал изменений
await page.goto(`${base}/operators`)
await page.waitForSelector('.p-datatable-tbody tr')
await page.waitForTimeout(500)
await shot('19-operators')
await page.goto(`${base}/audit`)
await page.waitForSelector('.p-datatable-tbody tr')
await page.locator('.p-datatable-tbody .p-datatable-row-toggle-button').first().click()
await page.waitForTimeout(500)
await shot('20-audit')

await browser.close()
console.log(`Скриншоты: ${out.pathname}`)
